shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  eslint-plugin-format: ^2.0.1
  eslint-plugin-pnpm: ^1.6.0
  lint-staged: ^15.4.1
  simple-git-hooks: ^2.11.1
  vue-i18n: ^11.3.2
catalogs:
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/tabler': ^1.2.33
    '@vitejs/plugin-vue': ^5.2.1
    eslint: ^10.2.1
    typescript: ^6.0.3
    unocss: ^66.0.0
    vite: ^6.0.7
    vue-tsc: ^2.2.0
  prod:
    '@vueuse/core': ^12.4.0
    pinia: ^2.3.0
    vue: ^3.5.13
    vue-router: ^4.5.0
