/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmationModal: typeof import('./components/common/ConfirmationModal.vue')['default']
    DashboardHeader: typeof import('./components/issues/DashboardHeader.vue')['default']
    IssueCard: typeof import('./components/issues/IssueCard.vue')['default']
    IssueDetailModal: typeof import('./components/issues/IssueDetailModal.vue')['default']
    IssueListSection: typeof import('./components/issues/IssueListSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
